# Generated by Django 4.0.4 on 2022-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='featurefunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=10)),
                ('lastupdateby', models.CharField(max_length=10)),
                ('updateat', models.DateTimeField()),
                ('flagid', models.IntegerField()),
                ('enable', models.BooleanField()),
            ],
        ),
    ]
